In [2]:
#HILL CIPHER
import numpy as np
def inverse(matrix, modulus):
    det = int(np.round(np.linalg.det(matrix))) % modulus
    det_inv = -1
    for i in range(1, modulus):
        if (det * i) % modulus == 1:
            det_inv = i
            break
    if det_inv == -1:
        raise ValueError("Matrix is not invertible modulo %d" % modulus)
    
    adjugate = det * np.linalg.inv(matrix)
    adjugate = np.round(adjugate).astype(int) % modulus
    inverse_matrix = (det_inv * adjugate) % modulus
    return inverse_matrix
    
def text_to_matrix(text, n):

    text = text.upper().replace(" ", "")
    padding = (n - len(text) % n) % n
    text += "X" * padding
    matrix = []
    for i in range(0, len(text), n):
        row = []
        for char in text[i:i + n]:
            row.append(ord(char) - ord('A'))
        matrix.append(row)
    return matrix

def matrix_to_text(matrix):
    #Converts a matrix of integers to a string of characters.
    
    text = ""
    for row in matrix:
        for val in row:
            text += chr(val + ord('A'))
    return text

def encrypt(plaintext, key):

    n = len(key)
    plaintext_matrix = text_to_matrix(plaintext, n)
    key_matrix = np.array(key)
    ciphertext_matrix = np.dot(plaintext_matrix, key_matrix) % 26
    return matrix_to_text(ciphertext_matrix)

def decrypt(ciphertext, key):
 
    n = len(key)
    ciphertext_matrix = text_to_matrix(ciphertext, n)
    key_matrix = np.array(key)
    key_inverse = inverse(key_matrix, 26)
    print(key_inverse)
    plaintext_matrix = np.dot(ciphertext_matrix, key_inverse) % 26
    return matrix_to_text(plaintext_matrix)

plaintext = input("Enter the text: ")
#key=input("Enter the key: ")
key=[[-24,18,5],[20,-15,-4],[-5,4,1]]
#key = [[3, 2], [5, 7]]  # Encryption key
ciphertext = encrypt(plaintext, key)
print("Encrypted text:", ciphertext)

decrypted_text = decrypt(ciphertext, key)
print("Decrypted text:", decrypted_text)

Enter the text: HAPPY
Encrypted text: REYFCC
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Decrypted text: HAPPYX
